name: Actualizaci칩n autom치tica TRIS

on:
  schedule:
    - cron: "5,35 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install pandas requests beautifulsoup4

      - name: Ejecutar bot
        run: python actualizar_tris.py

      - name: Guardar cambios
        run: |
          git config --global user.name "TrisBot"
          git config --global user.email "bot@tris.app"
          git add Tris.csv
          git commit -m "Actualizaci칩n autom치tica TRIS" || echo "Sin cambios"
          git push
